STAGING_DIR = '/data/tmp/'
DYNAMIC_CODE = "/data/dynlib/"
DAFNY_OUT = "/data/verified/"
DAFNY_BIN = "/usr/lib/dafny/dafny"
DAFNY_TARGET = '/compileTarget:py'
INPUT_DIR='/input/'
TEMPLATE_DIR='/templates/'
REPORT_DIR='/reports/'
BANDIT_TARGET='/scripts/'
DAFNY_PYTHON_SUFFIX = '-py'
